twitter-to-kafka-microservice:
  twitter-keywords:
    - Twitter
    - Kafka
    - Microservice
    - Demo
  sample-message: hello tq

  enable-mock-tweets: true
  mock-min-tweet-length: 5
  mock-max-tweet-length: 15
  mock-sleep-ms: 1000